[INFO -- 2018-12-03 15:46:18]
Starting flip_value script
version: 1.1
[INFO -- 2018-12-03 15:46:18]
Initialization strings:
[INFO -- 2018-12-03 15:46:18]
(1) file /home/latansini/carol-fi/carol-fi/codes/nnfulldup/nn-knl-files/nn
[INFO -- 2018-12-03 15:46:18]
(2) set args /home/latansini/carol-fi/carol-fi/codes/nnfulldup/nn-knl-files/filelist 20 5 5 /home/latansini/carol-fi/carol-fi/codes/nnfulldup/nn-knl-files/out20_5_5
[INFO -- 2018-12-03 15:46:18]
initSignal:0
[INFO -- 2018-12-03 15:46:18]
endSignal:2
[INFO -- 2018-12-03 15:46:18]
faultModel:4
[EXCEPTION -- 2018-12-03 15:46:19]
pythonException: invalid frame
[EXCEPTION -- 2018-12-03 15:46:19]
pythonException: invalid frame
[EXCEPTION -- 2018-12-03 15:46:19]
pythonException: invalid frame
[EXCEPTION -- 2018-12-03 15:46:19]
pythonException: invalid frame
[EXCEPTION -- 2018-12-03 15:46:19]
pythonException: invalid frame
[INFO -- 2018-12-03 15:46:19]
Backtrace BEGIN:
#0  0x00007ffff78d4e84 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007ffff78d2722 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007ffff76b0064 in start_thread (arg=0x7ffff42f6700) at pthread_create.c:309
#3  0x00007ffff73e562d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

178	    float target_lat, target_long;
179	    char * gold_filename, * filename;
180	    struct neighbor *data1 = NULL;
181	    struct neighbor *data2 = NULL;
182	
183	    if(argc < 6) {
184	        fprintf(stderr, "Invalid set of arguments:\n");
185	        fprintf(stderr, "%s <filelist> <num neighbors to find> <target latitude> <target longitude> <out filename>\n",argv[0]);
186	        exit(-1);
187	    }

Backtrace END
Memory content before bitflip:0x000x000xa00x40
Fault Model: LSB bit-flip
base address to flip value: 0x7fffffffe458
address max offset: 4
Memory content after  bitflip:0x000x000xa00x60
frame name: main
symbol name: target_long
symbol filename: nn.c
symbol line: 178
value: 9.22337204e+19
value address: 0x7fffffffe458
Type: A floating point type.
Type sizeof: 4

[INFO -- 2018-12-03 15:46:19]
Fault Injection Successful after 1.2161359787s
[EXCEPTION -- 2018-12-03 15:46:19]
pythonException: Thread no longer exists.
[INFO -- 2018-12-03 15:46:19]
event type: exit
[EXCEPTION -- 2018-12-03 15:46:19]
exit code: no exit code available
