[INFO -- 2018-12-03 09:39:31]
Starting flip_value script
version: 1.1
[INFO -- 2018-12-03 09:39:31]
Initialization strings:
[INFO -- 2018-12-03 09:39:31]
(1) file /home/latansini/carol-fi/carol-fi/codes/nnfulldup/nn-knl-files/nn
[INFO -- 2018-12-03 09:39:31]
(2) set args /home/latansini/carol-fi/carol-fi/codes/nnfulldup/nn-knl-files/filelist 20 5 5 /home/latansini/carol-fi/carol-fi/codes/nnfulldup/nn-knl-files/out20_5_5
[INFO -- 2018-12-03 09:39:31]
initSignal:0
[INFO -- 2018-12-03 09:39:31]
endSignal:2
[INFO -- 2018-12-03 09:39:31]
faultModel:1
[EXCEPTION -- 2018-12-03 09:39:32]
gdbException: Unterminated string in expression.
[EXCEPTION -- 2018-12-03 09:39:32]
pythonException: invalid frame
[EXCEPTION -- 2018-12-03 09:39:32]
pythonException: invalid frame
[EXCEPTION -- 2018-12-03 09:39:32]
pythonException: invalid frame
[EXCEPTION -- 2018-12-03 09:39:32]
pythonException: invalid frame
[EXCEPTION -- 2018-12-03 09:39:32]
pythonException: invalid frame
[INFO -- 2018-12-03 09:39:32]
Backtrace BEGIN:
#0  0x00007ffff78d4c79 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007ffff78d26e3 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007ffff76b0064 in start_thread (arg=0x7ffff62fa700) at pthread_create.c:309
#3  0x00007ffff73e562d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

88	dl-minimal.c: No such file or directory.

Backtrace END
Fliping a bit of the pointer
Memory content before bitflip:0x000x900x2f0xf50xff0x7f0x000x00
Fault Model: Double bit-flip
base address to flip value: 0x7fffffffdc70
address max offset: 8
Memory content after  bitflip:0x180x900x2f0xf50xff0x7f0x000x00
frame name: allocate_stack
symbol name: guard
symbol filename: allocatestack.c
symbol line: 646
value: 0x7ffff52f9000 ""
value address: 0x7fffffffdc70
Type: The type is a pointer.
Type sizeof: 8

[INFO -- 2018-12-03 09:39:32]
Fault Injection Successful after 1.26003789902s
[INFO -- 2018-12-03 09:39:32]
event type: exit
[EXCEPTION -- 2018-12-03 09:39:32]
exit code: no exit code available
[EXCEPTION -- 2018-12-03 09:39:32]
pythonException: Thread no longer exists.
[EXCEPTION -- 2018-12-03 09:39:32]
pythonException: Thread no longer exists.
